Updated sanity-checks.yml
shimman-dev/piscator pull request #27
Opened 2023-06-02 07:50 UTC by krishnaduttPanchagnula

2023-06-02 21:22 UTC, azemetre requested changes
This is a very great fix, thank you so much! I was going to make a PR where I turned coverage into an environment variable, which isn't necessary with your changes. Thank you once again.

I do have one request, I haven't had time to automatically enforce commit conventions. If you could amend your commit message and force push it back up, I can approve it.

You can use the following command if needed:

```
git commit --amend -m 'build(actions): removing `set-output` command'
```

The reason for this is I'm trying out a little experiment with this repo where everything is an atomic commit that gets rebased into main.

- [ ] amend current commit message

2023-06-03 11:01 UTC, krishnaduttPanchagnula commented
done @azemetre

2023-06-03 22:21 UTC, azemetre approved these changes

2023-06-03 22:25 UTC, merged

2023-06-03 22:28 UTC, azemetre commented
Thank you so much @krishnaduttPanchagnula for the contribution :D